import { useRef, useState } from "react";
import { ApiError, consumePlanAction, planApi, runApi, type PlanReference, type PlanView } from "@/lib/api";
import { planStore } from "@/lib/plan-store";
export function PlanDecisionControls({ plan, reference, allowDecision, allowRunControls }: { plan: PlanView; reference: PlanReference; allowDecision: boolean; allowRunControls: boolean }) {
  const [feedback, setFeedback] = useState(""); const [pending, setPending] = useState<string | null>(null); const [message, setMessage] = useState(""); const retry = useRef<{ fingerprint: string; id: string } | null>(null);
  const submit = async (action: "approve" | "reject" | "revise") => { if (action === "revise" && !feedback.trim()) return setMessage("Revision feedback is required."); if (action === "reject" && !window.confirm("Reject this Plan and cancel its waiting run?")) return; const text = action === "revise" ? feedback.trim() : null; const fingerprint = JSON.stringify([action, text, plan.current_version, plan.aggregate_version]); const decision_id = retry.current?.fingerprint === fingerprint ? retry.current.id : crypto.randomUUID(); retry.current = { fingerprint, id: decision_id }; setPending(action); setMessage(""); try { const response = await planApi.decision(plan.plan_id, { session_id: reference.session_id, decision_id, plan_version: plan.current_version, expected_version: plan.aggregate_version, action, feedback: text }); await consumePlanAction(response, planStore.acceptDataPart); await planStore.refresh(reference); retry.current = null; setFeedback(""); setMessage("Plan action completed."); } catch (error) { if (error instanceof ApiError && error.status === 409) setMessage("Plan changed; review the latest version."); else setMessage(error instanceof Error ? error.message : "Plan action failed."); await planStore.refresh(reference); } finally { setPending(null); } };
  const runAction = async (action: string, request: () => Promise<Response>) => { setPending(action); setMessage(""); try { await consumePlanAction(await request(), planStore.acceptDataPart); await planStore.refresh(reference); setMessage("Run action completed."); } catch (error) { setMessage(error instanceof Error ? error.message : "Run action failed."); await planStore.refresh(reference); } finally { setPending(null); } };
  const active = plan.active_run_id !== null && ["running", "resuming", "awaiting_user"].includes(plan.run_status ?? ""); const disabled = pending !== null;
  return <div className="plan-controls">{allowDecision && <><textarea value={feedback} maxLength={8000} disabled={disabled} aria-label="Revision feedback" onChange={(e) => setFeedback(e.target.value)} /><div><button disabled={disabled} onClick={() => void submit("approve")}>Approve</button><button disabled={disabled} onClick={() => void submit("revise")}>Request revision</button><button disabled={disabled} onClick={() => void submit("reject")}>Reject</button></div></>}{allowRunControls && active && plan.active_run_id && <button disabled={disabled} onClick={() => void runAction("cancel", () => runApi.cancel(plan.active_run_id!, reference.session_id))}>Cancel run</button>}{allowRunControls && plan.summary_retry_available && plan.active_run_id && <button disabled={disabled} onClick={() => void runAction("retry-summary", () => runApi.retrySummary(plan.active_run_id!, reference.session_id))}>Retry summary</button>}{allowRunControls && plan.status === "approved" && !active && <button disabled={disabled} onClick={() => void runAction("rerun", () => planApi.rerun(plan.plan_id, reference.session_id))}>Run again</button>}<p aria-live="polite">{message}</p></div>;
}
